name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Get version form file
      uses: pCYSl5EDgo/cat@master
      id: fileVersion
      with: 
        path: src/version.txt

    - name: Echo version number
      run: echo $VERSION
      env:
        VERSION: ${{steps.fileVersion.outputs.text}}.${{GITHUB_RUN_NUMBER}}

    - name: Restore dependencies
      run: dotnet restore ./src/MDD4All.SpecIF.DataModels/MDD4All.SpecIF.DataModels.csproj

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{ steps.fileVersion.outputs.text }}.${{GITHUB_RUN_NUMBER}} ./src/MDD4All.SpecIF.DataModels/MDD4All.SpecIF.DataModels.csproj

#    - name: Test
#      run: dotnet test --no-build --verbosity normal
